### ISSUE TITLE
apollo_sv failing in owl2json

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#116]
java.lang.NullPointerException: Cannot read field "types" because "bnode" is null
	at uk.ac.ebi.owl2json.OwlGraph.writeProperties(OwlGraph.java:362)
	at uk.ac.ebi.owl2json.OwlGraph.writeNode(OwlGraph.java:309)
	at uk.ac.ebi.owl2json.OwlGraph.write(OwlGraph.java:242)
	at uk.ac.ebi.owl2json.OWL2JSON.main(OWL2JSON.java:147)

**Comment by jamesamcl** [comment]
This is because of something weird in the ontology with the oboInOwl properties:

http://purl.obolibrary.org/obo/apollo_sv.owl

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0007562">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0071684"/>
        <obo:IAO_0000115 xml:lang="en">The emergence of an adult insect from a pupa case.</obo:IAO_0000115>
        <obo:IAO_0000412 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://purl.org/obo/owl/gene_ontology</obo:IAO_0000412>
        <oboInOwl:hasDbXref>
            <rdf:Description/>
        </oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>
            <rdf:Description/>
        </oboInOwl:hasDbXref>
        <oboInOwl:hasDefinition>
            <rdf:Description/>
        </oboInOwl:hasDefinition>
        <oboInOwl:hasDefinition>
            <rdf:Description/>
        </oboInOwl:hasDefinition>
        <oboInOwl:hasOBONamespace>biological_process</oboInOwl:hasOBONamespace>
        <rdfs:label xml:lang="en">eclose</rdfs:label>
        <rdfs:label xml:lang="en">eclosion</rdfs:label>
    </owl:Class>
    

`oboInOwl:hasDbXref` etc. point to bnodes with no properties.
