### ISSUE TITLE
`findByIdAndIsDefiningOntology` not working for ro

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#141]
OLS3

```json
{
  "_embedded": {
    "properties": [
      {
        "_links": {
          "self": {
            "href": "<base>/api/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0001019?lang=en"
          }
        },
        "annotation": {
          "editor preferred term": [
            "contains"
          ],
          "temporal interpretation": [
            "http://purl.obolibrary.org/obo/RO_0001901"
          ]
        },
        "description": [],
        "has_children": false,
        "iri": "http://purl.obolibrary.org/obo/RO_0001019",
        "is_defining_ontology": true,
        "is_obsolete": false,
        "is_root": true,
        "label": "contains",
        "lang": "en",
        "obo_id": "RO:0001019",
        "ontology_iri": "http://purl.obolibrary.org/obo/ro.owl",
        "ontology_name": "ro",
        "ontology_prefix": "RO",
        "short_form": "RO_0001019",
        "synonyms": []
      }
    ]
  },
  "_links": {
    "self": {
      "href": "<base>/api/properties/findByIdAndIsDefiningOntology"
    }
  },
  "page": {
    "number": 0,
    "size": 20,
    "totalElements": 1,
    "totalPages": 1
  }
}
```

OLS4

```json
{
  "_links": {
    "self": {
      "href": "<base>/api/properties/findByIdAndIsDefiningOntology?short_form=RO_0001019&page=0&size=20"
    }
  },
  "page": {
    "number": 0,
    "size": 20,
    "totalElements": 0,
    "totalPages": 0
  }
}
```

**Comment by jamesamcl** [comment]
This might just be because ro is failing to load:

```
--- Loading ontology: ro
load ontology from: http://purl.obolibrary.org/obo/ro.owl
Using predownloaded file for http://purl.obolibrary.org/obo/ro.owl
Downloading http://purl.obolibrary.org/obo/ro.owl took 0s
import: http://purl.obolibrary.org/obo/ro/annotations.owl
Using predownloaded file for http://purl.obolibrary.org/obo/ro/annotations.owl
Downloading http://purl.obolibrary.org/obo/ro/annotations.owl took 0s
import: http://purl.obolibrary.org/obo/ro/chemical.owl
Using predownloaded file for http://purl.obolibrary.org/obo/ro/chemical.owl
org.apache.jena.riot.RiotException: [line: 1, col: 1 ] Content is not allowed in prolog.
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:153)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$ErrorHandlerBridge.fatalError(ReaderRIOTRDFXML.java:313)
	at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:978)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:101)
	at org.apache.jena.rdfxml.xmlinput.ARP.load(ARP.java:118)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.parse(ReaderRIOTRDFXML.java:188)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.read(ReaderRIOTRDFXML.java:86)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:353)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:343)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:292)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:540)
	at uk.ac.ebi.owl2json.OwlGraph.parseRDF(OwlGraph.java:62)
	at uk.ac.ebi.owl2json.OwlGraph.<init>(OwlGraph.java:147)
	at uk.ac.ebi.owl2json.OWL2JSON.main(OWL2JSON.java:140)
```

http://purl.obolibrary.org/obo/ro/chemical.owl is in OBO format

**Comment by jamesamcl** [comment]
Issue opened with RO https://github.com/oborel/obo-relations/issues/673
