### ISSUE TITLE
backend java.lang.OutOfMemoryError at EBI

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#392]
we hit this when under heavy load:

```
Exception in thread "http-nio-8080-Poller" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:801)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:984)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.executeInternal(ThreadPoolExecutor.java:1480)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1402)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1188)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.processKey(NioEndpoint.java:873)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:840)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by henrietteharmse** [comment]
Seemed to be resolved by additional K8s resources.
