### ISSUE TITLE
Add the Earth Metabolome Initiative (EMI) ontology

### ISSUE THREAD

**Issue by tarcisiotmf** [EBISPOT/ols4#814]
Please find below the filled request form:
 
[EMI OLS ontology request.xlsx](https://github.com/user-attachments/files/18061997/EMI.OLS.ontology.request.xlsx)

Please, let me know if you need any further information from us.

Thank you very much!

Best regards,
Tarcisio Mendes de Farias

**Comment by haideriqbal** [comment]
Hi @tarcisiotmf! I've tried to load this ontology into OLS but at the moment one of the imports (http://www.linkedmodel.org/schema/dtype) is not been able to get processed by the OLS. The reason being JENA parser which OLS uses to parse ontology files can't determine the content type of the file.

When you open the file in the browser you see an XML file but for JENA to process the file, it need to have `Content-Type` HTTP header which this particular import doesn't have. See below:

```
curl -I http://www.linkedmodel.org/schema/dtype

HTTP/1.1 200 OK
Date: Tue, 10 Dec 2024 13:07:57 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade
Last-Modified: Tue, 14 Nov 2023 22:20:42 GMT
ETag: "156120f-5d8f-60a24327cf6e0"
Accept-Ranges: bytes
Content-Length: 23951
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
```

So my suggestion at this stage would be if possible you can get rid of this import. As I see from the linkedmodel.org website that it isn't being maintained actively, last update was in 2016 and dtype ontology itself was updated in 2011. Or you can try to reach out to linkedmodel people to get it sorted out.

In the meanwhile, I would try to see on our end if we can find a work around in OLS to process the ontology files not having HTTP `Content-Type` header in the request.

**Comment by tarcisiotmf** [comment]
Thank you very much for considering and looking at it. Actually, we are not importing directly the "http://www.linkedmodel.org/schema/dtype" ontology as you can see in the original file, but it is being imported by one of our imported ontologies, namely, https://qudt.org/schema/qudt/ . Therefore, it is an import of an imported ontology.  For your information, [qudt](https://qudt.org) that imports dtype seems to be actively maintained  as you can see in the bottom of its page (Generated 2024-09-20T17:35:35.094-07:00).

Meanwhile, may you consider the following purl to fetch the ontology? I've removed the qudt import. Thank you very much!

ontology_purl: https://purl.org/emi/ols
 
**Remark**: depending on the nature of the ontology and its application, it is indeed better to not change often over time. Particularly, the dtype ontology is to define data types that are not covered by [xsd](http://www.w3.org/2001/XMLSchema#) that is not being updated since 2004 and in use by the OWL 2 specification, from the "dtype" description: 

> The ontology "dtype" provides a specification of simple data types such as enumerations and codelists. These are needed in support of the conversion of XML Schemas and UML Models to OWL. The purpose of "dtype" is to provide a foundation for expressing rich data types. These data types are typically needed when dealing with OWL representations of data structures derived from XML Schema.

**Comment by henrietteharmse** [comment]
@tarcisiotmf Thanks for removing qudt!

We completely agree that some ontologies do not get updated for good reason. A good example of this in OLS is BFO, which is an 
upper ontology. 

I think the concern here is more that the [http://www.linkedmodel.org/](http://www.linkedmodel.org/schema/dtype) website has a number of dead links. In particular, the link to "DTYPE 1.2", clearly indicating the intension for a later version of DTYPE. Same goes for "VAEM 2.0",  "VOAG SCHEMA 2.0", etc., with no update wrt the status of any of these. Our intension was to reach out to them to help resolve this issue. But with no update to the website since 2016, that approach does not seem viable.

**Comment by tarcisiotmf** [comment]
Yes, you are right. I think this issue should be pointed out to the quadt maintainers (https://www.qudt.org/pages/QUDTcontactsPage.html) since it is an alive project that reuses "dtype 1.0" and "vaem".  I will try to reach them to solve this issue. 

In any case, for the EMI ontology it is not critical for us to not consider  the "quadt" import at OLS. This is also because specially in our case we are only importing quadt to just be able to assign units with the controlled vocabulary (https://qudt.org/2.1/vocab/unit) via the property qudt:hasUnit that does not depend on dtype or veam vocabularies. Moreover, we are not (directly) importing "dtype" or "veam" that is part of the quadt schema that is not being reused by the EMI ontology. 

Thanks again for your help!  Please let me know if you have any issue to load the https://purl.org/emi/ols file with Jena.

**Comment by haideriqbal** [comment]
@tarcisiotmf new ontology file works fine with OLS. It will be available in production within 48 hours.

**Comment by tarcisiotmf** [comment]
Thanks!

**Comment by tarcisiotmf** [comment]
@haideriqbal apparently the ontology is not anymore available at OLS. May you add it again and consider change the persistent URL from purl.org/emi/ols to https://w3id.org/emi/ols to fetch the ontology? We are migrating our persistent urls to w3id service for a better support of our needs. Thank you very much for your support on this!

**Comment by mdrishti** [comment]
@haideriqbal, just for our knowledge, how long does it take for the new ontology to reflect on OLS4?

**Comment by haideriqbal** [comment]
@mdrishti, It usually updates within 48 hours

**Comment by mdrishti** [comment]
@haideriqbal, the EMI ontology is not still available on OLS, even though the latest update was on 12th Aug. Do we need to change anything in the specifications of the ontology?

**Comment by haideriqbal** [comment]
@mdrishti i can load the ontology locally when setting the ontology_purl to this:

https://raw.githubusercontent.com/earth-metabolome-initiative/earth_metabolome_ontology/refs/heads/main/emi-ols.ttl

which is what https://w3id.org/emi/ols this redirects to ... but when using this https://w3id.org/emi/ols OLS is throwing following error:

```
21:15:31.463 [main] INFO  uk.ac.ebi.rdf2json.RDF2JSON - --- Loading ontology: emi
21:15:31.463 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - load ontology from: https://w3id.org/emi/ols
21:15:31.465 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: Using predownloaded file for https://w3id.org/emi/ols
21:15:31.470 [main] ERROR org.apache.jena.riot - [line: 1, col: 1 ] Content is not allowed in prolog.
21:15:31.470 [main] DEBUG uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: unable to use predownloaded file for https://w3id.org/emi/ols
21:15:31.470 [main] ERROR uk.ac.ebi.rdf2json.OntologyGraph - parseRDF: Downloading (not predownloaded) https://w3id.org/emi/ols
21:15:31.951 [main] ERROR org.apache.jena.riot - [line: 1, col: 1 ] Content is not allowed in prolog.
21:15:31.953 [main] ERROR uk.ac.ebi.rdf2json.RDF2JSON - Error processing ontology emi: [line: 1, col: 1 ] Content is not allowed in prolog.
org.apache.jena.riot.RiotException: [line: 1, col: 1 ] Content is not allowed in prolog.
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:153)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$ErrorHandlerBridge.fatalError(ReaderRIOTRDFXML.java:313)
	at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:978)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:114)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)

```

which means the type of content is not being recognised by OLS. Is it possible if you can change the url to use `https://w3id.org/emi/ols.ttl`?

**Comment by mdrishti** [comment]
@haideriqbal thanks for looking into this. I changed the url to https://w3id.org/emi/ols.ttl. Have a look here https://github.com/EBISPOT/ols4/pull/954 . Not sure what I might have done wrong with the pull-request. Let me know please and I will edit it accordingly.

**Comment by tarcisiotmf** [comment]
Hi all, I think this re-opened issue is still not solved. I have looked at https://www.ebi.ac.uk/ols4/ontologies today and I do not see this ontology in the catalog. Did you figure out what is the problem? Please let us know if it is an issue from our side. Thanks for your help on this!

**Comment by haideriqbal** [comment]
@tarcisiotmf this still need to go into production. We implemented the fix in the dev. I'll merge the changes in the production today and it'll be updated in production within 48 hours.
