### ISSUE TITLE
JENA Parser throw Error if HTTP Content Type Header not present

### ISSUE THREAD

**Issue by haideriqbal** [EBISPOT/ols4#815]
At present, if there is not `Content Type` header present in the ontology URL then the parser throws 

```
org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=http://www.linkedmodel.org/schema/dtype : stream=null)
ols4-dataload-1  |      at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:317)
ols4-dataload-1  |      at org.apache.jena.riot.RDFParser.parse(RDFParser.java:296)
ols4-dataload-1  |      at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:540)
ols4-dataload-1  |      at uk.ac.ebi.rdf2json.OntologyGraph.parseRDF(OntologyGraph.java:92)
ols4-dataload-1  |      at uk.ac.ebi.rdf2json.OntologyGraph.<init>(OntologyGraph.java:165)
ols4-dataload-1  |      at uk.ac.ebi.rdf2json.RDF2JSON.main(RDF2JSON.java:147)

```

This issue is blocking loading of EMI ontology specified here: https://github.com/EBISPOT/ols4/issues/814

Ideal solution would be if there is any setting in the JENA parser to interpret the content type without the content-type header.

**Comment by jamesamcl** [comment]
I think this should be fixed upstream by the webserver that distributes the ontology. we shouldn't have to guess the format

**Comment by jamesamcl** [comment]
Also I would be very happy if https://github.com/EBISPOT/ols4/pull/762 could be reviewed before making changes in this area or it will no longer be applicable

**Comment by haideriqbal** [comment]
closing this as James point makes sense
